name: storyboard_view_annotation
description: A new Flutter package project.
version: 0.0.1
author: HelloCore
homepage: https://github.com/HelloCore/storyboard_view

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
