name: storyboard_view_generator
description: A new Flutter package project.
version: 0.0.1
author: HelloCore
homepage: https://github.com/HelloCore/storyboard_view

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^1.2.2
  source_gen: ^0.9.4+2
  code_builder: ^3.2.0
  analyzer: ^0.39.3
  storyboard_view_annotation: ^0.0.1
  glob: ^1.1.7

dev_dependencies:
  build_runner: ^1.0.0